### ISSUE TITLE
download link broken

### ISSUE THREAD

**Issue by arosenhagen** [steverobbins/magedownload-cli#16]
http://magedownload.steverobbins.com/download/latest/magedownload.phar is currently not reachable (empty response)

Edit: I saw your last commit removed the link to this location. This just broke my MageTestStand (automated) setup. I switched to getting the latest release from github - although it's not that easy to always get the latest release location. Save to close though.

**Comment by steverobbins** [comment]
Apologize.  Was cleaning up some hosting things and decided to switch to GitHub as the download source.  Seeing as even curl downloads weren't working for a month I didn't think it would hurt anything critical.
